# -*- coding: utf-8 -*-
"""finalandfixed(3).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kQrDVGw9-aAUsU-IrvOYNzRnU9GLzDdL
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
data_set= pd.read_csv("/content/T1.csv")

data_set.info()
data_set.isnull().any()

data_1=data_set.copy()

#Giving proper names to columns
data_1.rename(columns={'LV ActivePower (kW)':'ActivePower(kW)',"Wind Speed (m/s)":"WindSpeed(m/s)","Wind Direction (°)":"Wind_Direction"},
                inplace=True)
data_1.drop(columns=['Date/Time'],axis = 1,inplace = True)
data_1.head()

#deleting False Data
data_2 = data_1[((data_1['WindSpeed(m/s)']>=3.3) & (data_1['ActivePower(kW)']>0)) | ((data_1['WindSpeed(m/s)']>3.3) & (data_1['Theoretical_Power_Curve (KWh)']>0))]

data_2.head()

Wind_data=data_2['Wind_Direction'].copy()

Theri=data_2['Theoretical_Power_Curve (KWh)'].copy()

data_2.drop(columns = ['Wind_Direction'],inplace = True)

data_2.head()

data_2['Theoretical_Power_Curve (KWh)'] = Theri

data_2.rename(columns= {
    'Theoretical_Power_Curve (KWh)' : 'Theoretical_Power'
})

data_2.insert(0,'Wind_Direction',Wind_data)

data_2.head()

AP= data_2['ActivePower(kW)']
data_2.drop('ActivePower(kW)',inplace = True,axis = 1)

data_2.insert(2,'Active Power',AP)

dic = dict()
for i in range(len(data_2)):
  s = str(i)
  dic[s] = i

len(dic)

li=list(dic.values())

data_2['index'] = li

data_2.set_index('index',inplace = True)

data_2.head()

x = data_2.iloc[:,0:3].values

y = data_2.iloc[:,3:4].values

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.33,random_state = 0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

y_pred = regressor.predict(x_test)

import pickle
pickle.dump(regressor,open('Power.pkl','wb'))

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

sol = regressor.predict([[270,10.27,4000],[80.502724,11.404030,1780]])

sol